### ISSUE TITLE
sqlite3_exec: unable to open database file

### ISSUE THREAD

**Issue by abcSup** [Siguza/imobax#2]
When the program runs, it outputs the following error:
```
$ imobax -l ./backup
sqlite3_exec: unable to open database file
```
**My 'hacky' Solution**
First, I was thinking that it might be due to not properly configured permissions of the respective folder or files. I have tried to grant the folder and files write permission, but still it does not work.

Therefore, I tried opening the `Manifest.db` using the `sqlite3` command which works without any permission errors. I ran the following command:
```
$ sqlite3 backup/Manifest.db 
sqlite> .tables
Files       Properties
sqlite> ^D
$
```
And this leaves the folder with two new temp files in the folder which sqlite3 did not remove upon closing – `Manifest.db-shm` `Manifest.db-wal`. After that, `imobax -l ./backup` works normally.

I have not tried to dive into the code yet. But I suspect that the problem might be in `db.c` when calling the `sqlite3_open_v2` function, although the function `sqlite3_open_v2` succeeds without any error.

**Addition Information**
The permission of the `backup` directory
`drwxr-xr-x   3 user  staff  96 May  7 13:02 backup`
The permission of the `Manifest.db`
`-rw-r--r--@ 1 user  staff  61911040 May  7 13:02 Manifest.db`

**Comment by Siguza** [comment]
What version of macOS are you using, and what version of iOS created the backup in question?  
Particularly, is it possible that the SQLite version on iOS is newer than the version of your SQLite library on macOS? (Running the `file` command on the `.db` should tell you the exact version that was used.)

**Comment by abcSup** [comment]
I did not think about that for the moment, thank you for pointing that out. 

Currently, I am on macOS Mojave Version 10.14.4. And the backup is created from a iPhone 6 Plus running iOS 12.1 on the same Mac today.

```
$ sqlite3 -version
3.24.0 2018-06-04 14:10:15 95fbac39baaab1c3a84fdfc82ccb7f42398b2e92f18a2a57bce1d4a713cbaapl
$ file backup/Manifest.db
backup/Manifest.db: SQLite 3.x database, user version 2, last written using SQLite version 3024000
````

**Comment by abcSup** [comment]
After completely remove my backup and backup again, the program works perfectly. I guess previously, the backup was somehow corrupted. Besides, the current backup contains those two files initially – `Manifest.db-shm``Manifest.db-wal` so I think they might be the cause of the previous problem.

Sorry for the trouble, I appreciate your help and efforts

**Comment by Siguza** [comment]
Sure, no problem.  
Closing this as resolved then.
